### PR TITLE
Check if render is present before loading

### PR DESCRIPTION
**Pull request by GreeFine**
When refreshing the page i got : 
Uncaught (in promise) TypeError: window.grecaptcha.render is not a function
Added render to be checked to avoid this error

### CODE REVIEW

**Comment by szchenghuang** [comment]
Thank you for flagging.

I do assume the existence of `window.grecaptcha` implies the existence of `window.grecaptcha.render`. While it seems not a valid assumption in your case, can you elaborate how to unfold the issue?

So that you know `if (window.grecaptcha.render)` will throw an error when `grecaptcha` is not hooked on `window` yet. Such alteration will not be merged. But a fuller check like ` if (window.grecaptcha && window.grecaptcha.render)` do help in a way.

The root cause of not having `render` should be spotted. I believe there is something to improve if I am able to reproduce it. I dont really get what you mean by refreshing the page.

**Comment by GreeFine** [comment]
@szchenghuang Hey, thx for taking the time !

i don't realy understand it either, it happens 1/2 i refresh my page, here is 2 two screen where i just pressed F5 once in between, if i keep pressing the same goes on(one page fine the other one crash).

From the looking tho, you can see the trigger is caused by rehydrate function of my redux **persist** store, so maybe with this setup you might be able to reproduce it, 



Sorry for my poor english i am not an native speaker but i hope you can understand me well :)

**Comment by szchenghuang** [comment]
@GreeFine, that screenshot does help.

The odd in it is that somehow `render` got cleared from `recaptcha` (while it had been present). Since the object `window.recaptcha` is manipulated by Google's recaptcha script, I honestly have no fix for it except a defensive guard as mentioned in your and my earlier comments. Since the guard is healthy, I am going to merge your PR and tweak it a bit as such.

Please make sure the recaptcha script was not loaded twice, #1, which could be related.

If you have any observation next, please let me know. Thanks!

**Comment by JustFly1984** [comment]
I've encountered the same issue, and it was happen only for android users. Long time we could not figure that out, until I installed custom yandex metrica script (don't use `react-yandex-metrica` it is buggy)

I've made new `recaptcha-v3-react@2.0.0` package, which does not load script second time, but you need to provide an id to initialization object. Also I added onSuccess and onError callbacks, so you could do something, if scripts doesn't load.

**Pull request merged**
